### PR TITLE
POPs

### PR DESCRIPTION
**Pull request by sf-dcp**
Successful run [here](https://github.com/NYCPlanning/data-engineering/actions/runs/9763311636/job/26952594359).

### CODE REVIEW

**Review by alexrichey — CHANGES_REQUESTED** [review]
Awesome! Thank you so much. One quick change, the bytes link is broken on the draft version. If you look at the LION metadata files, there's a bytes url you can copy. Then after that, go ahead and publish that revision you created.

**Comment by sf-dcp** [comment]
> Awesome! Thank you so much. One quick change, the bytes link is broken on the draft version. If you look at the LION metadata files, there's a bytes url you can copy. Then after that, go ahead and publish that revision you created.

Are you referring to this part? 

image

If yes, the link does open for me (I use safari browser), but I can revise to what you have in LION!

**Comment by alexrichey** [comment]
Yep, that's the one. It's the one I was complaining about on teams a week or two ago.

**Review by alexrichey — APPROVED** [review]
Awesome, thanks! Just confirming, you published the revision on Socrata?

**Comment by sf-dcp** [comment]
> Awesome, thanks! Just confirming, you published the revision on Socrata?

Done! [link](https://data.cityofnewyork.us/City-Government/Privately-Owned-Public-Spaces-POPS-/rvih-nhyn/about_data)

**Pull request merged**
