### PR TITLE
FacDB 24Q1

### PR DESCRIPTION
**Pull request by damonmcc**
successful github action run [here](https://github.com/NYCPlanning/data-engineering/actions/runs/9751286640/job/26912535332#step:7:37)

### CODE REVIEW

**Comment by alexrichey** [comment]
Awesome! I am wondering though if we can document the `why` for the metadata changes, e.g. the removal of the standardized values, column name changes, etc. Either in the body of the commit message (my preference) or on the PR?

**Comment by damonmcc** [comment]
@alexrichey I'll add to the commit message

I think the column metadata mismatch can be fixed using `column_details ... api_name ... display_name` like in COLP's metadata. will give that a shot!

**Comment by damonmcc** [comment]
@alexrichey good run [here](https://github.com/NYCPlanning/data-engineering/actions/runs/9751286640/job/26912535332#step:7:37)!

**Review by alexrichey — APPROVED** [review]
Makes me so happy! Also, glad to see our changes removed the funky formatting in column descriptions

**Pull request merged**
